### ISSUE TITLE
NPR All Things Considered update failed on 2024-05-10

### ISSUE THREAD

**Issue by mgn0000** [pyther/podfeed#12]
There was no update from the NPR All Things Considered feed for May 10th 2024, did they change the website again?

**Comment by pyther** [comment]
Thanks for reporting this. There was no program show data for May 9, 2024 and the code didn't know how to handle that. This has been fixed in https://github.com/pyther/podfeed/commit/16b9582c55cca53ccde92658305074a66ce367ab.

<img width="491" alt="image" src="https://github.com/pyther/podfeed/assets/88368/a2e12fb6-87a3-4d03-9389-60ecedf2f779">

**Comment by mgn0000** [comment]
Sorry I forgot to close it myself. I should know better, was in the business myself for years.

**Comment by mgn0000** [comment]
Just noticed that the NPR morning edition feed failed this morning. MattOn Jun 15, 2024, at 15:56, Matthew Gyurgyik ***@***.***> wrote:﻿
Closed #12 as completed.
